services:
  - type: web
    name: library-system
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: library-db
          property: connectionString

databases:
  - name: library-db
